# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"

[build.processing]
  [build.processing.secrets_scanning]
    # Ignore specific paths where secrets are being detected
    # This is an alternative because omit_keys wasn't reliably working
    omit_paths = [
      "pages/api/publish.ts",
      ".netlify/.next/cache/webpack/server-production/",
      ".netlify/.next/server/pages/api/publish.js",
      ".netlify/.next/standalone/.next/server/pages/api/publish.js",
      ".netlify/functions-internal/___netlify-server-handler/.next/server/pages/api/publish.js"
    ] 