# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"

[build.processing]
  [build.processing.secrets_scanning]
    # Ignore specific keys detected by the scanner
    # These are used server-side only in the publish API route
    omit_keys = ["GITHUB_AUTHOR_NAME", "GITHUB_AUTHOR_EMAIL"] 