# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  [build.processing.secrets_scanning]
    omit_paths = [".netlify/**"] 