# Decap CMS Configuration
# See https://decapcms.org/docs/configuration-options/

# This file will be configured in the next steps. 

backend:
  name: git-gateway
  branch: main
local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

# Tell Decap CMS to load the global CSS for previews
registerPreviewStyle: "/app/globals.css"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Image URL", name: "imageUrl", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "thinkers"
    label: "Thinkers"
    folder: "content/thinkers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}